### ISSUE TITLE
Config not being saved into file

### ISSUE THREAD

**Issue by Mythos** [Hirtol/PartyScreenEnhancements#7] opened 2021-02-13 20:51 UTC
Hey there,
I'm using the 1.5.7 version of your mod, and it works fine so far.
The only thing I noticed is that the config is not being persisted.
Upon starting the game I have to set the sorting options and general options again.

I've checked my `Documents\Mount and Blade II Bannerlord\Configs` path, but there's no `Mods` folder or a `PartyScreenEnhancements.xml`.

In the log files I also couldn't find anything like `PSE Config Load Exception`.

**Comment by Mythos** [comment] 2021-02-13 20:57
Quick followup as I found out how to "fix" the problem:
You have to manually create the `Mods` folder.

Probably a quick
```csharp
if(!Directory.Exists(Directories.MOD_DIR))
{
	Directory.Create(Directories.MOD_DIR);
}
```
should do it.
I only had `ModLogs` and `ModSettings` maybe created by other mods.

**Comment by Hirtol** [comment] 2021-02-15 15:45
Thanks for the report!

The issue is due to the new logging functionality I added in the latest version. The `Directory.Create()` call was being done after the logging initialization (which tries to create a file in the mod dir, which in your case wouldn't exist yet and thus throw an exception, canceling the latter `Directory.Create()` call).

Apologies for the negligence, thankfully those exceptions are caught so should at worst be a minor annoyance.
I'll push a fix for it in a bit and it will be included in the next version.

**Closed as completed** 2021-02-15 15:48 UTC
